# Setup
title:               spflueger's blog
tagline:             'Post about Science and IT'
description:         ''
url:                 https://spflueger.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Stefan Pflüger
  url:                
  email:              

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
